/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waylens_hachi_ui_services_download_HttpRemuxer */

#ifndef _Included_com_waylens_hachi_ui_services_download_HttpRemuxer
#define _Included_com_waylens_hachi_ui_services_download_HttpRemuxer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waylens_hachi_ui_services_download_HttpRemuxer_EVENT_FINISHED
#define com_waylens_hachi_ui_services_download_HttpRemuxer_EVENT_FINISHED 0L
#undef com_waylens_hachi_ui_services_download_HttpRemuxer_EVENT_ERROR
#define com_waylens_hachi_ui_services_download_HttpRemuxer_EVENT_ERROR 1L
#undef com_waylens_hachi_ui_services_download_HttpRemuxer_EVENT_PROGRESS
#define com_waylens_hachi_ui_services_download_HttpRemuxer_EVENT_PROGRESS 2L
/*
 * Class:     com_waylens_hachi_ui_services_download_HttpRemuxer
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waylens_hachi_ui_services_download_HttpRemuxer_native_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_waylens_hachi_ui_services_download_HttpRemuxer
 * Method:    native_release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waylens_hachi_ui_services_download_HttpRemuxer_native_1release
  (JNIEnv *, jobject);

/*
 * Class:     com_waylens_hachi_ui_services_download_HttpRemuxer
 * Method:    native_set_iframe_only
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_ui_services_download_HttpRemuxer_native_1set_1iframe_1only
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_waylens_hachi_ui_services_download_HttpRemuxer
 * Method:    native_setAudio
 * Signature: (ZLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_ui_services_download_HttpRemuxer_native_1setAudio
  (JNIEnv *, jobject, jboolean, jstring, jstring);

/*
 * Class:     com_waylens_hachi_ui_services_download_HttpRemuxer
 * Method:    native_run
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_ui_services_download_HttpRemuxer_native_1run
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_waylens_hachi_ui_services_download_HttpRemuxer
 * Method:    native_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waylens_hachi_ui_services_download_HttpRemuxer_native_1finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
