/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waylens_hachi_snipe_remix_AvrproFilter */

#ifndef _Included_com_waylens_hachi_snipe_remix_AvrproFilter
#define _Included_com_waylens_hachi_snipe_remix_AvrproFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_smart_filter_init
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1smart_1filter_1init
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_smart_filter_is_data_parsed
 * Signature: (ILcom/waylens/hachi/snipe/remix/AvrproClipInfo;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1smart_1filter_1is_1data_1parsed
  (JNIEnv *, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_smart_filter_feed_data
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1smart_1filter_1feed_1data
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_smart_filter_read_results
 * Signature: (IZ)Lcom/waylens/hachi/snipe/remix/AvrproSegmentInfo;
 */
JNIEXPORT jobject JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1smart_1filter_1read_1results
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_smart_filter_deint
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1smart_1filter_1deint
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_lap_timer_filter_init
 * Signature: (Lcom/waylens/hachi/snipe/remix/AvrproClipInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1lap_1timer_1filter_1init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_lap_timer_set_start
 * Signature: (ILcom/waylens/hachi/snipe/remix/AvrproGpsParsedData;)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1lap_1timer_1set_1start
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_lap_timer_feed_gps_data
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1lap_1timer_1feed_1gps_1data
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_lap_timer_read_results
 * Signature: (I)Lcom/waylens/hachi/snipe/remix/AvrproLapTimerResult;
 */
JNIEXPORT jobject JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1lap_1timer_1read_1results
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waylens_hachi_snipe_remix_AvrproFilter
 * Method:    native_avrpro_lap_timer_deinit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_waylens_hachi_snipe_remix_AvrproFilter_native_1avrpro_1lap_1timer_1deinit
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
